[tool.poetry]
name = "dogpicsbot"
version = "2.0.0"
description = "A simple Telegram bot that sends random dog pictures (and more!)."
authors = ["Andrés Ignacio Torres <dev@aitorres.com>"]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^1.0.0"
python-telegram-bot = "^20.6"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
ipython = "^8.17.2"
flake8 = "^6.1.0"
black = "^24.3.0"
pre-commit = "^3.5.0"
isort = "^5.12.0"
pylint = "^3.0.2"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-trio = "^0.8.0"
pytest-tornasync = "^0.6.0.post2"

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 100
