[tool.poetry]
name = "dogpicsbot"
version = "3.1.1"
description = "A simple Telegram bot that sends random dog pictures (and more!)."
authors = ["Andrés Ignacio Torres <dev@aitorres.com>"]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.1.0"
python-telegram-bot = "^21.10"
requests = "^2.32.3"

[tool.poetry.dev-dependencies]
flake8 = "^7.2.0"
black = "^25.1.0"
pre-commit = "^4.2.0"
isort = "^6.0.1"
pylint = "^3.3.6"
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
pytest-trio = "^0.8.0"
pytest-tornasync = "^0.6.0.post2"

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 100
