on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    name: Run tests in Python ${{ matrix.python-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
      - name: Lint with flake8
        run: poetry run flake8
      - name: Run tests with pytest
        run: poetry run pytest
      - name: Lint project with pylint
        run: poetry run pylint *.py
